apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: sahilkr1302/product-service:test
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              value: admin123
            - name: DB_NAME
              value: cloudcart